INSERT INTO items (`name`, `label`, `limit`, `can_remove`, `weight`, `usable`, `description`) VALUES
('americanflag', 'American Flag', 1, 1, 0.5, 1, 'Deploys American Flag'),
('mexicanflag', 'Mexican Flag', 1, 1, 0.5, 1, 'Deploys Mexican Flag'),
('canadaflag', 'Canada Flag', 1, 1, 0.5, 1, 'Deploys Canada Flag'),
('piratesflag', 'Pirate Flag', 1, 1, 0.5, 1, 'Deploys Pirate Flag'),
('lgbtqflag', 'LGBTQ Flag', 1, 1, 0.5, 1, 'Deploys LGBTQ Flag'),
('gypsyflag', 'Gypsy Flag', 1, 1, 0.5, 1, 'Deploys Gypsy Flag'),
('irishflag', 'Irish Flag', 1, 1, 0.5, 1, 'Deploys Irish Flag'),
('ukflag', 'Uk Flag', 1, 1, 0.5, 1, 'Deploys Uk Flag'),
('brflag', 'Brasil Flag', 1, 1, 0.5, 1, 'Deploys Brasil Flag'),
('frflag', 'France Flag', 1, 1, 0.5, 1, 'Deploys France Flag'),
('itflag', 'Italia Flag', 1, 1, 0.5, 1, 'Deploys Italia Flag'),
('jmflag', 'Jamaica Flag', 1, 1, 0.5, 1, 'Deploys Jamaica Flag'),
('gerflag', 'Germany Flag', 1, 1, 0.5, 1, 'Deploys Germany Flag'),
('confflag', 'Confederation Flag', 1, 1, 0.5, 1, 'Deploys Confederation Flag'),
('unionflag', 'Union Flag', 1, 1, 0.5, 1, 'Deploys Union Flag'),
('lemoyne1flag', 'Lemoyne State Flag', 1, 1, 0.5, 1, 'Deploys Lemoyne State Flag'),
('newhannover1flag', 'New Hannover State Flag', 1, 1, 0.5, 1, 'Deploys New Hannover State Flag'),
('westelizabeth1flag', 'West Elizabeth State Flag', 1, 1, 0.5, 1, 'Deploys West Elizabeth State Flag'),
('newaustin1flag', 'New Austin State Flag', 1, 1, 0.5, 1, 'Deploys New Austin State Flag'),
('ambarino1flag', 'Ambarino State Flag', 1, 1, 0.5, 1, 'Deploys Ambarino State Flag'),
('comancheflag', 'Comanche Tribe Flag', 1, 1, 0.5, 1, 'Deploys Comanche Tribe Flag'),
('navajoflag', 'Navajo Tribe Flag', 1, 1, 0.5, 1, 'Deploys Navajo Tribe Flag'),
('lakotaflag', 'Lakota Council Tribe Flag', 1, 1, 0.5, 1, 'Deploys Lakota Council Tribe Flag'),
('inuitflag', 'Inuit Tribe Flag', 1, 1, 0.5, 1, 'Deploys Inuit Tribe Flag'),
('australiaflag', 'Australia Flag', 1, 1, 0.5, 1, 'Deploys Australia Flag'),
('belgiumflag', 'Belgium Flag', 1, 1, 0.5, 1, 'Deploys Belgium Flag'),
('cataloniaflag', 'Catalonia Flag', 1, 1, 0.5, 1, 'Deploys Catalonia Flag'),
('chinaflag', 'China Flag', 1, 1, 0.5, 1, 'Deploys China Flag'),
('cubaflag', 'Cuba Flag', 1, 1, 0.5, 1, 'Deploys Cuba Flag'),
('czechflag', 'Czech Republic Flag', 1, 1, 0.5, 1, 'Deploys Czech Republic Flag'),
('denmarkflag', 'Denmark Flag', 1, 1, 0.5, 1, 'Deploys Denmark Flag'),
('finlandflag', 'Finland Flag', 1, 1, 0.5, 1, 'Deploys Finland Flag'),
('guarmaflag', 'Guarma Flag', 1, 1, 0.5, 1, 'Deploys Guarma Flag'),
('hungaryflag', 'Hungary Flag', 1, 1, 0.5, 1, 'Deploys Hungary Flag'),
('kuwaitflag', 'Kuwait Flag', 1, 1, 0.5, 1, 'Deploys Kuwait Flag'),
('flandresflag', 'Flanders Flag', 1, 1, 0.5, 1, 'Deploys Flanders Flag'),
('newzealandflag', 'New Zealand Flag', 1, 1, 0.5, 1, 'Deploys New Zealand Flag'),
('philippinesflag', 'Philippines Flag', 1, 1, 0.5, 1, 'Deploys Philippines Flag'),
('polandflag', 'Poland Flag', 1, 1, 0.5, 1, 'Deploys Poland Flag'),
('portugalflag', 'Portugal Flag', 1, 1, 0.5, 1, 'Deploys Portugal Flag'),
('puertoricoflag', 'Puerto Rico Flag', 1, 1, 0.5, 1, 'Deploys Puerto Rico Flag'),
('russiaflag', 'Russia Flag', 1, 1, 0.5, 1, 'Deploys Russia Flag'),
('saudiflag', 'Saudi Arabia Flag', 1, 1, 0.5, 1, 'Deploys Saudi Arabia Flag'),
('serbiaflag', 'Serbia Flag', 1, 1, 0.5, 1, 'Deploys Serbia Flag'),
('spainflag', 'Spain Flag', 1, 1, 0.5, 1, 'Deploys Spain Flag'),
('swedenflag', 'Sweden Flag', 1, 1, 0.5, 1, 'Deploys Sweden Flag'),
('thailandflag', 'Thailand Flag', 1, 1, 0.5, 1, 'Deploys Thailand Flag'),
('turkeyflag', 'Turkey Flag', 1, 1, 0.5, 1, 'Deploys Turkey Flag'),
('ukraineflag', 'Ukraine Flag', 1, 1, 0.5, 1, 'Deploys Ukraine Flag'),
('whiteflag', 'White Flag', 1, 1, 0.5, 1, 'Deploys White Flag'),
('whitelongflag', 'White Flag Long', 1, 1, 0.5, 1, 'Deploys White Flag Long'),
('redflag', 'Red Flag', 1, 1, 0.5, 1, 'Deploys Red Flag'),
('lemoynelongflag', 'Lemoyne Flag', 1, 1, 0.5, 1, 'Deploys Lemoyne Flag'),
('ambarinoflag', 'Ambarino Flag', 1, 1, 0.5, 1, 'Deploys Ambarino Flag'),
('newhanoverflag', 'New Hanover Flag', 1, 1, 0.5, 1, 'Deploys New Hanover Flag'),
('westelizabethflag', 'West Elizabeth Flag', 1, 1, 0.5, 1, 'Deploys West Elizabeth Flag'),
('newaustinflag', 'New Austin Flag', 1, 1, 0.5, 1, 'Deploys New Austin Flag'),
('flaggang01', 'Gang Flag 01', 1, 1, 0.5, 1, 'Deploys Gang Flag 01'),
('flaggang02', 'Gang Flag 02', 1, 1, 0.5, 1, 'Deploys Gang Flag 02'),
('flaggang03', 'Gang Flag 03', 1, 1, 0.5, 1, 'Deploys Gang Flag 03'),
('flaggang04', 'Gang Flag 04', 1, 1, 0.5, 1, 'Deploys Gang Flag 04'),
('flaggang05', 'Gang Flag 05', 1, 1, 0.5, 1, 'Deploys Gang Flag 05'),
('flaggang06', 'Gang Flag 06', 1, 1, 0.5, 1, 'Deploys Gang Flag 06'),
('flaggang07', 'Gang Flag 07', 1, 1, 0.5, 1, 'Deploys Gang Flag 07'),
('flaggang08', 'Gang Flag 08', 1, 1, 0.5, 1, 'Deploys Gang Flag 08'),
('flaggang09', 'Gang Flag 09', 1, 1, 0.5, 1, 'Deploys Gang Flag 09'),
('flaggang10', 'Gang Flag 10', 1, 1, 0.5, 1, 'Deploys Gang Flag 10'),
('flaggang11', 'Gang Flag 11', 1, 1, 0.5, 1, 'Deploys Gang Flag 11'),
('flaggang12', 'Gang Flag 12', 1, 1, 0.5, 1, 'Deploys Gang Flag 12');