INSERT INTO items (item, label, `limit`, can_remove, type, usable, groupId, metadata, `desc`, degradation, weight) VALUES
('americanflag', 'American Flag', 10, 1, 'item_standard', 1, 1, '{}', 'American Flag', 0, 0.5),
('mexicanflag', 'Mexican Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Mexican Flag', 0, 0.5),
('canadaflag', 'Canada Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Canada Flag', 0, 0.5),
('piratesflag', 'Pirate Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Pirate Flag', 0, 0.5),
('lgbtqflag', 'LGBTQ Flag', 10, 1, 'item_standard', 1, 1, '{}', 'LGBTQ Flag', 0, 0.5),
('gypsyflag', 'Gypsy Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Gypsy Flag', 0, 0.5),
('irishflag', 'Irish Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Irish Flag', 0, 0.5),
('ukflag', 'Uk Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Uk Flag', 0, 0.5),
('brflag', 'Brasil Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Brasil Flag', 0, 0.5),
('frflag', 'France Flag', 10, 1, 'item_standard', 1, 1, '{}', 'France Flag', 0, 0.5),
('itflag', 'Italia Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Italia Flag', 0, 0.5),
('jmflag', 'Jamaica Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Jamaica Flag', 0, 0.5),
('gerflag', 'Germany Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Germany Flag', 0, 0.5),
('confflag', 'Confederation Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Confederation Flag', 0, 0.5),
('unionflag', 'Union Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Union Flag', 0, 0.5),
('lemoyne1flag', 'Lemoyne State Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Lemoyne State Flag', 0, 0.5),
('newhannover1flag', 'New Hannover State Flag', 10, 1, 'item_standard', 1, 1, '{}', 'New Hannover State Flag', 0, 0.5),
('westelizabeth1flag', 'West Elizabeth State Flag', 10, 1, 'item_standard', 1, 1, '{}', 'West Elizabeth State Flag', 0, 0.5),
('newaustin1flag', 'New Austin State Flag', 10, 1, 'item_standard', 1, 1, '{}', 'New Austin State Flag', 0, 0.5),
('ambarino1flag', 'Ambarino State Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Ambarino State Flag', 0, 0.5),
('comancheflag', 'Comanche Tribe Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Comanche Tribe Flag', 0, 0.5),
('navajoflag', 'Navajo Tribe Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Navajo Tribe Flag', 0, 0.5),
('lakotaflag', 'Lakota Council Tribe Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Lakota Council Tribe Flag', 0, 0.5),
('inuitflag', 'Inuit Tribe Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Inuit Tribe Flag', 0, 0.5),
('australiaflag', 'Australia Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Australia Flag', 0, 0.5),
('belgiumflag', 'Belgium Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Belgium Flag', 0, 0.5),
('cataloniaflag', 'Catalonia Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Catalonia Flag', 0, 0.5),
('chinaflag', 'China Flag', 10, 1, 'item_standard', 1, 1, '{}', 'China Flag', 0, 0.5),
('cubaflag', 'Cuba Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Cuba Flag', 0, 0.5),
('czechflag', 'Czech Republic Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Czech Republic Flag', 0, 0.5),
('denmarkflag', 'Denmark Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Denmark Flag', 0, 0.5),
('finlandflag', 'Finland Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Finland Flag', 0, 0.5),
('guarmaflag', 'Guarma Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Guarma Flag', 0, 0.5),
('hungaryflag', 'Hungary Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Hungary Flag', 0, 0.5),
('kuwaitflag', 'Kuwait Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Kuwait Flag', 0, 0.5),
('flandresflag', 'Flanders Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Flanders Flag', 0, 0.5),
('newzealandflag', 'New Zealand Flag', 10, 1, 'item_standard', 1, 1, '{}', 'New Zealand Flag', 0, 0.5),
('philippinesflag', 'Philippines Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Philippines Flag', 0, 0.5),
('polandflag', 'Poland Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Poland Flag', 0, 0.5),
('portugalflag', 'Portugal Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Portugal Flag', 0, 0.5),
('puertoricoflag', 'Puerto Rico Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Puerto Rico Flag', 0, 0.5),
('russiaflag', 'Russia Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Russia Flag', 0, 0.5),
('saudiflag', 'Saudi Arabia Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Saudi Arabia Flag', 0, 0.5),
('serbiaflag', 'Serbia Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Serbia Flag', 0, 0.5),
('spainflag', 'Spain Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Spain Flag', 0, 0.5),
('swedenflag', 'Sweden Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Sweden Flag', 0, 0.5),
('thailandflag', 'Thailand Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Thailand Flag', 0, 0.5),
('turkeyflag', 'Turkey Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Turkey Flag', 0, 0.5),
('ukraineflag', 'Ukraine Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Ukraine Flag', 0, 0.5),
('whiteflag', 'White Flag', 10, 1, 'item_standard', 1, 1, '{}', 'White Flag', 0, 0.5),
('whitelongflag', 'White Flag Long', 10, 1, 'item_standard', 1, 1, '{}', 'White Flag Long', 0, 0.5),
('redflag', 'Red Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Red Flag', 0, 0.5),
('lemoynelongflag', 'Lemoyne Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Lemoyne Flag', 0, 0.5),
('ambarinoflag', 'Ambarino Flag', 10, 1, 'item_standard', 1, 1, '{}', 'Ambarino Flag', 0, 0.5),
('newhanoverflag', 'New Hanover Flag', 10, 1, 'item_standard', 1, 1, '{}', 'New Hanover Flag', 0, 0.5),
('westelizabethflag', 'West Elizabeth Flag', 10, 1, 'item_standard', 1, 1, '{}', 'West Elizabeth Flag', 0, 0.5),
('newaustinflag', 'New Austin Flag', 10, 1, 'item_standard', 1, 1, '{}', 'New Austin Flag', 0, 0.5),
('flaggang01', 'Gang Flag 01', 10, 1, 'item_standard', 1, 1, '{}', 'Gang Flag 01', 0, 0.5),
('flaggang02', 'Gang Flag 02', 10, 1, 'item_standard', 1, 1, '{}', 'Gang Flag 02', 0, 0.5),
('flaggang03', 'Gang Flag 03', 10, 1, 'item_standard', 1, 1, '{}', 'Gang Flag 03', 0, 0.5),
('flaggang04', 'Gang Flag 04', 10, 1, 'item_standard', 1, 1, '{}', 'Gang Flag 04', 0, 0.5),
('flaggang05', 'Gang Flag 05', 10, 1, 'item_standard', 1, 1, '{}', 'Gang Flag 05', 0, 0.5),
('flaggang06', 'Gang Flag 06', 10, 1, 'item_standard', 1, 1, '{}', 'Gang Flag 06', 0, 0.5),
('flaggang07', 'Gang Flag 07', 10, 1, 'item_standard', 1, 1, '{}', 'Gang Flag 07', 0, 0.5),
('flaggang08', 'Gang Flag 08', 10, 1, 'item_standard', 1, 1, '{}', 'Gang Flag 08', 0, 0.5),
('flaggang09', 'Gang Flag 09', 10, 1, 'item_standard', 1, 1, '{}', 'Gang Flag 09', 0, 0.5),
('flaggang10', 'Gang Flag 10', 10, 1, 'item_standard', 1, 1, '{}', 'Gang Flag 10', 0, 0.5),
('flaggang11', 'Gang Flag 11', 10, 1, 'item_standard', 1, 1, '{}', 'Gang Flag 11', 0, 0.5),
('flaggang12', 'Gang Flag 12', 10, 1, 'item_standard', 1, 1, '{}', 'Gang Flag 12', 0, 0.5);
